### PR TITLE
Tolerance, centers, and points

### PR DESCRIPTION
**Pull request by ksunden**
TODO: Write explicit test for this. 
Would also like explicit assertions in existing tests for centers and points being present and properly shaped.

@darienmorrow do you have a dataset that I can use which fails (to be properly read in, not necessarily failing to read in at all) on current development?

Also test agianst:

- [x] cobalamin paper
- [x] Darien active paper[s]
- [x] bearclaw paper [using existing file, and run from scratch]

### CODE REVIEW

**Comment by ksunden** [comment]
failed test was due to #553 , rerunning

**Comment by darienmorrow** [comment]
@ksunden I think #587 has some data that will fail `development` when it gets chopped. Can you download the data and see if it is what you need? If not, I can trudge through my archive.

**Comment by darienmorrow** [comment]
Are the comments starting on [line 99](https://github.com/wright-group/WrightTools/blob/tolerance_inf/WrightTools/data/_pycmds.py#L99) necessary still? 

Can we provide some documentation in the docstring for how tolerances now work?

**Comment by ksunden** [comment]
Breaks in `join` for certain datas (where we are joining different dimensioned scans

Should make `join` use the set of variables which are in all datas to be joined

**Comment by ksunden** [comment]
Travis timed out, I'm not sure what happened, but it didn't _start_ the actual tests until around 45 minutes in, so

**Pull request merged**
