### PR TITLE
Remotely fetch logo so it apears on PyPI

### PR DESCRIPTION
**Pull request by ksunden**

### CODE REVIEW

**Comment by ksunden** [comment]
Confirmed it appears on README.rst as rendered here on github

**Comment by untzag** [comment]
@ksunden any way to get github to respect the scaling? it's silly how large the logo is...

**Comment by ksunden** [comment]
Not that I know of, Github s rst reading is sometimes lacking

**Comment by ksunden** [comment]
Maybe if we switched to markdown, since pypi supports that now

**Pull request merged**
