### PR TITLE
Validate units are in the unit registry on set

### LINKED ISSUE #1010: raise friendly exception if unit string not in registry
Currently if a unit doesn't subscribe to an unstated style guide, things like chop and split fail (and by extension our artists). Is this desired behavior? Or should a user be able to specify any unit they desire (e.g. a unit of `'excitons/s'` is a valid physical unit but it causes a units error). 

```
import numpy as np
import WrightTools as wt

values = np.linspace(-1,1,51)
arr = np.linspace(0,1,51)

# works as expected 
d = wt.Data(name='test1')
d.create_variable('B', values=values, units='T')
d.transform('B')
d.create_channel('arr', values=arr)
wt.artists.quick1D(d)

# works as expected 
d = wt.Data(name='test2')
d.create_variable('B', values=values, units='tesla')
d.transform('B')
d.create_channel('arr', values=arr)
wt.artists.quick1D(d)

# fails at chop
d = wt.Data(name='test3')
d.create_variable('B', values=values, units='Tesla')
d.transform('B')
d.create_channel('arr', values=arr)
wt.artists.quick1D(d)
```

```
UnitsError: (UnitsError(...), 'expected units of () (recieved Tesla)')
```

### PR DESCRIPTION
**Pull request by ksunden**
Closes #1010

## Changes

Add `@property` for units to validate that they are in the registry for setting the units on axis, channel, and variable (the latter two handled by the common parent, Group)

## Checklist

- [x] added tests, if applicable
- [x] updated documentation, if applicable
- [x] updated CHANGELOG.md
- [x] tests pass

### CODE REVIEW

**Comment by ksunden** [comment]
@darienmorrow if you wish to play with this, that would be appreciated. Would you like to see tests of failing sets added?

**Comment by darienmorrow** [comment]
```
values = np.linspace(-1,1,51)
arr = np.linspace(0,1,51)
d = wt.Data(name='test3')
d.create_variable('B', values=values, units='Tesla')
d.transform('B')
```
This code raises a `ValueError` on the `transform` line, NOT on the `create_variable` line. Is this desired?

**Comment by darienmorrow** [comment]
@ksunden Can you check that my tests are fine. For some reason, pytest is broken on my machine.

**Comment by ksunden** [comment]
Whoops, added it to Group, when I should have added it to Dataset, will fix in a bit

**Review by darienmorrow — APPROVED** [review]

**Pull request merged**
