### PR TITLE
map_variable:  ignore filepath

### PR DESCRIPTION
**Pull request by ddkohler**
## Changes

map_variable ignores its filepath kwarg when creating new data, which improperly initialized variables and channels to prevent interpolation.  

Fixes issue #1039 

## Checklist

- [x] added tests, if applicable
- [x] updated CHANGELOG.md
- [x] tests pass

### CODE REVIEW

**Comment by ddkohler** [comment]
@ksunden would you mind taking a look at what is happening with `test_excess_data_kwarg_3D`?  Raises a new error in `Group.__new__`:
```
Traceback (most recent call last):
  File "c:/Users/Dan/Documents/source/WrightTools/tests/data/map_variable.py", line 60, in <module>
    test_excess_data_kwarg_3D()
  File "c:/Users/Dan/Documents/source/WrightTools/tests/data/map_variable.py", line 48, in test_excess_data_kwarg_3D
    mapped = data.map_variable("w2", 11)
  File "c:\users\dan\documents\source\wrighttools\WrightTools\data\_data.py", line 1144, in map_variable
    out = Data(**kwargs)
  File "c:\users\dan\documents\source\wrighttools\WrightTools\_group.py", line 37, in __call__
    return cls.__new__(cls, *args, **kwargs)
  File "c:\users\dan\documents\source\wrighttools\WrightTools\_group.py", line 168, in __new__
    raise Exception  # TODO: better exception
Exception
```

**Comment by ddkohler** [comment]
problem solved--error is analogous to our "filepath" issue, but for the "edit_local" attribute, which was set to true as default in wt5 v1.0.0 .  Test now passes, but will be skipped because 3D interpolation takes forever.

**Comment by kameyer226** [comment]
I'll bite...why is `pop` working but not `get`?

**Comment by ddkohler** [comment]
@kameyer226 sorry I forgot to link the issue this PR applies too--see the discussion for #1039 .  `pop` takes `filepath` out of kwargs so it is not used later to populate attrs.

**Review by kameyer226 — APPROVED** [review]
A+

**Pull request merged**
