### PR TITLE
Explicitly store axes as fixed width numpy strings

### PR DESCRIPTION
**Pull request by ksunden**
Needed for compatibility with bluesky/tiled (via msgpack_numpy)

## Changes

please describe your changes here :smiley:

## Checklist

- [x] added tests, if applicable
- [x] updated documentation, if applicable
- [x] updated CHANGELOG.md
- [x] tests pass

### CODE REVIEW

**Comment by untzag** [comment]
@ksunden consider adding integration tests for tiled here?

**Comment by kameyer226** [comment]
Guess this is an important decision here...maybe we should all sign off on this

**Comment by ksunden** [comment]
@kameyer226 why do you think this is an important decision? this is one of the smallest effective changes I've proposed to any project recently. it really doesn't change all that much from the users point of view, just stores strings in a better way for cross language support and for integration with one particular library

**Comment by ksunden** [comment]
No, it just means that all values shorter than the longest are null padded as stored, rather than being variable length as stored. There is almost no direct impact for users.

**Comment by ksunden** [comment]
For reference, this is how we store all the other things like variable names and channel names

**Review by kameyer226 — APPROVED** [review]

**Pull request merged**
