### PR TITLE
Ensure factor is multiplied on symmetric_sqrt

### LINKED ISSUE #926: Symmetric square root does not correctly multiple by the sign factor when the output array is supplied
https://github.com/wright-group/WrightTools/blob/e875360573e8375f94ed4ed70a7d8dc02ab92bb5/WrightTools/kit/_calculate.py#L145-L165

### PR DESCRIPTION
**Pull request by ksunden**
Closes #926

### CODE REVIEW

**Comment by untzag** [comment]
gosh @ksunden I do NOT understand the bug---can you explain it to me?

**Comment by ksunden** [comment]
Wihout this change:

```
>>> a = np.linspace(-9, 9, 10)
>>> a
array([-9., -7., -5., -3., -1.,  1.,  3.,  5.,  7.,  9.])
>>> wt.kit.symmetric_sqrt(a)
array([-3.        , -2.64575131, -2.23606798, -1.73205081, -1.        ,
        1.        ,  1.73205081,  2.23606798,  2.64575131,  3.        ])
>>> o = np.empty_like(a)
>>> wt.kit.symmetric_sqrt(a, out=o)
array([-3.        , -2.64575131, -2.23606798, -1.73205081, -1.        ,
        1.        ,  1.73205081,  2.23606798,  2.64575131,  3.        ])
>>> o
array([3.        , 2.64575131, 2.23606798, 1.73205081, 1.        ,
       1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ])
>>>
```
With this change:
```

>>> a = np.linspace(-9, 9, 10)
>>> a
array([-9., -7., -5., -3., -1.,  1.,  3.,  5.,  7.,  9.])
>>> wt.kit.symmetric_sqrt(a)
array([-3.        , -2.64575131, -2.23606798, -1.73205081, -1.        ,
        1.        ,  1.73205081,  2.23606798,  2.64575131,  3.        ])
>>> o = np.empty_like(a)
>>> wt.kit.symmetric_sqrt(a, out=o)
array([-3.        , -2.64575131, -2.23606798, -1.73205081, -1.        ,
        1.        ,  1.73205081,  2.23606798,  2.64575131,  3.        ])
>>> o
array([-3.        , -2.64575131, -2.23606798, -1.73205081, -1.        ,
        1.        ,  1.73205081,  2.23606798,  2.64575131,  3.        ])
>>>
```

Note the difference in the sign of the negative valued inputs.

The `out` parameter is meant to avoid reallocating the output array (As it does in numpy functions)

Without this change, the returned array is a reallocated array (by the `*` operator), and the provided output array is _not_ multiplied by the sign.

I can add a test if desired, this was mostly me finding a small change to walk through an example of opening up a pull request with @kameyer226 watching (but it does have an associated issue)

**Comment by untzag** [comment]
@ksunden I think adding a test would be nice, but feel free to merge if you wish

**Comment by darienmorrow** [comment]
@ksunden pretty sure that test isn't gonna pass. sqrt(9) != 0

**Comment by ksunden** [comment]
@darienmorrow, this is symmetric sqrt, not normal sqrt, the whole point being that negative numbers have negative output, I did in fact run the test locally and it did pass

**Comment by darienmorrow** [comment]
@ksunden I guess I don't understand the test, then. I thought the test was asserting that sym_sqrt([-9, 9_[sic]_, 3]) = [-3, 0, 3] which just isn't true even considering float vs. int map.

**Comment by ksunden** [comment]
@darienmorrow I initially misread your comment, I updated to reflect what you actually said, sorry for the confusion.

It is not asserting that `symmeric_sqrt([-9,9,3]) == [-3, 0, 3]`, it is asserting that `symmeric_sqrt([-9,0,9]) == [-3, 0, 3]`

**Comment by darienmorrow** [comment]
@ksunden I see my problem! 😬 I read `np.array([-9,9,3])` when your test actually has `np.linspace(-9, 9, 3)`. Gosh this is embarrassing.

**Comment by ksunden** [comment]
No worries, all good now

**Pull request merged**
