### PR TITLE
Convert verbose

### PR DESCRIPTION
**Pull request by darienmorrow**
## Changes

Propagates verbose kwarg to convert for data.split

## Checklist

- [x] updated CHANGELOG.md
- [x] tests pass

### CODE REVIEW

**Comment by ksunden** [comment]
In this instance, I may actually lean towards calling convert with `verbose=False` it is an implementation detail, not something the user really ever needs to know... in fact line 1756 converts it back so it is only converted during computation (and that line needs the same kwarg passed regardless)

**Comment by darienmorrow** [comment]
@ksunden I could be wrong: I recall that axes, constants, etc _do not_ have `verbose` exposed. So it should not be passed to them. The reason it is set to `True` is that we generally have `verbose` set to True throughout the entire stack. I would actually prefer if `verbose=False` was the norm in the stack.

**Comment by ksunden** [comment]
Okay... arguably the axis/constant/variable `convert` methods _should_ have the verbose flag (and handle the verbose printing)


But further, I think that here we should be using the axis convert rather than the data convert... we don't want or need to convert constants or variables (the latter is not done anyway as we don't pass the kwarg) and we just transformed so there is only one axis.

**Comment by ksunden** [comment]
But my point of "this is an implementation detail that does not need to be printed _ever_ stands

**Comment by darienmorrow** [comment]
@ksunden I think I have done what you desired. If you desire something different, can you make the changes yourself?

**Review by ksunden — APPROVED** [review]

**Review by untzag — APPROVED** [review]

**Pull request merged**
