### PR TITLE
BUG: fix expected units behavior in from_PyCMDS

### LINKED ISSUE #755: from_PyCMDS:  retrieve units for filling unfinished data
When importing data that isn't filled to the shape reported in header, values of axes are assigned based on header content, but the units are not read.  Example at https://drive.google.com/open?id=1ta8AEOR-Ck3IENRAHkYbyIjumHP0oiii

```
d = wt.data.from_PyCMDS(...)
print(d.w1.points)
```

### PR DESCRIPTION
**Pull request by ksunden**
Closes #755

### CODE REVIEW

**Comment by ksunden** [comment]
LGTM appears to be having problems at the moment, the failure is happing on checking out master, not anything to do with this commit

**Comment by ksunden** [comment]
Test failures stem from the change of using axes in the hardware native units vs that which was set for the axis itself in "axis units"

I _think_ we want to use the "axis units" (this was mentioned by @darienmorrow in #755), but would like to reach a consensus before changing the tests and merging code which changes behavior in a backwards incompatible way.

**Comment by ksunden** [comment]
@untzag @p770193 @darienmorrow Any opinions?

**Comment by untzag** [comment]
@ksunden yes let's change this behavior---axes should inherit units from headers

**Comment by untzag** [comment]
@ksunden is this ready for review?

**Comment by ksunden** [comment]
@untzag yes it is

**Pull request merged**
