### PR TITLE
add JOSS as intended citation

### PR DESCRIPTION
**Pull request by untzag**
## Changes

Add citation file.

## Checklist

- [ ] added tests, if applicable
- [ ] updated documentation, if applicable
- [ ] updated CHANGELOG.md
- [ ] tests pass

### CODE REVIEW

**Comment by untzag** [comment]
Doesn't do what I want :no_entry:

**Comment by ksunden** [comment]
@untzag what was wrong with this?

**Comment by untzag** [comment]
GitHub doesn't parse the citation the way I want it to.

**Comment by ksunden** [comment]
But what was wrong with how it parsed it... I think this sounds like a good idea, from what I can tell... nothing is obviously wrong with the file you generated... what was wrong with it?  why did you give up?

**Comment by untzag** [comment]
This is the citation that GitHub generates. It's simply not correct for citing a journal article like we wish to.

```bibtex
@misc{Thompson_WrightTools_a_Python_2019,
author = {Thompson, Blaise J. and Sunden, Kyle F. and Darien, Morrow J. and Kohler, Daniel D. and Wright, John C.},
doi = {10.21105/joss.01141},
month = {1},
title = {WrightTools: a Python package for multidimensional spectroscopy},
year = {2019}
}
```

**Comment by ksunden** [comment]
https://github.com/citation-file-format/citation-file-format/blob/main/test/1.0.3/software-with-reference/CITATION.cff

For consideration

**Pull request closed without merging**
