### PR TITLE
Return min and max when file is read only

### PR DESCRIPTION
**Pull request by ksunden**
## Changes

avoid caching min and max when it write is unavailable, still return

## Checklist

- [x] added tests, if applicable
- [NA] updated documentation, if applicable 
- [x] updated CHANGELOG.md
- [ ] tests pass

### CODE REVIEW

**Comment by untzag** [comment]
> added tests, if applicable

I'd like there to be a test for this behavior. Your implementation looks great.

**Review by untzag — APPROVED** [review]

**Comment by ksunden** [comment]
Tests added

**Comment by ksunden** [comment]
weird seg fault from not explicitly closing the files, the tests actually do pass, though, updated with the explicit close

**Review by untzag — APPROVED** [review]

**Comment by untzag** [comment]
thanks @ksunden , merge whenever :smile:

**Pull request merged**
