### PR TITLE
update alternatives page

### LINKED ISSUE #851: add Gwyddion to "alternatives" page?

### PR DESCRIPTION
**Pull request by untzag**
in response to https://github.com/openjournals/joss-reviews/issues/1141#issuecomment-450850266
resolves #851

### CODE REVIEW

**Comment by darienmorrow** [comment]
@untzag I don't think this resolves #851. Can we add a link to Gwyddion?

**Comment by untzag** [comment]
@darienmorrow sorry you caught me in the middle of my TODO list

the WIP tag is off---ready for review

**Comment by darienmorrow** [comment]
@untzag Sorry, I didn't see the WIP tag :disappointed:

**Comment by ksunden** [comment]
Do we wish to comment on the maintenance status of some of these projects, for instance, PyTra is to my knowledge unmaintained since 2012 or so

**Pull request merged**
