### PR TITLE
documentation

### PR DESCRIPTION
**Pull request by untzag**
please delete documentation branch after merge

### CODE REVIEW

**Comment by ksunden** [comment]
I will add a commit addressing the trailing whitespace, please wait for that before merging

**Comment by ksunden** [comment]
Actually, let's try this out:


@pep8speaks pep8ify

**Comment by darienmorrow** [comment]
@ksunden Do you have any problem with me merging?

**Comment by ksunden** [comment]
Yes, still want to clear up those whitespace warnings

Was trying to get the bot to do it, but it doesn't seem to have listened to me

**Comment by darienmorrow** [comment]
@ksunden Ok, I leave it to you to fix and then merge 😎

**Comment by ksunden** [comment]
I am going to give it a few minutes with the current request to pep8ify, but I'm learning it may be better to just pull it down and run `autopep8` myself

**Comment by ksunden** [comment]
I also want to generate the html to check that all appears as desired

**Comment by ksunden** [comment]
I believe the changes I pushed address my concerns, but will revisit in the morning to make sure

**Pull request merged**
