### PR TITLE
Lgtm fixes

### PR DESCRIPTION
**Pull request by ksunden**
Fixes several problems identified by looking at https://lgtm.com/projects/g/wright-group/WrightTools/

Mostly just clean up/removing unused variable/imports, but some meatier changes that fix real issues we either had not experienced or didn't properly attribute.

Please do request tests if there are things that stand out as needing them.
I am going to suggest that tests for `join` be added when that is rewritten, not this second.

### CODE REVIEW

**Comment by ksunden** [comment]
This pull request **introduces 1 alert** and **fixes 22** when merging be0d58b46317847a05e9bba331e786d9c020e25f into f22920579f45632b4123661d9832ff0cc1b614c4 - [view on LGTM.com](https://lgtm.com/projects/g/wright-group/WrightTools/rev/pr-93ae352fc0a31e6ec5d1bd277d8336460a12a4d3)

**new alerts:**

* 1 for Unused import

**fixed alerts:**

* 11 for Unused local variable
* 5 for Unused import
* 3 for &#39;import \*&#39; may pollute namespace
* 1 for Except block handles &#39;BaseException&#39;
* 1 for Suspicious unused loop iteration variable
* 1 for Nested loops with same variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ksunden** [comment]
This pull request **fixes 22 alerts** when merging 058352fb8123c107addff5e0246e978050438891 into f22920579f45632b4123661d9832ff0cc1b614c4 - [view on LGTM.com](https://lgtm.com/projects/g/wright-group/WrightTools/rev/pr-f38db5605eaa13bbb6af0efb98d5cbe7330d94e9)

**fixed alerts:**

* 11 for Unused local variable
* 5 for Unused import
* 3 for &#39;import \*&#39; may pollute namespace
* 1 for Except block handles &#39;BaseException&#39;
* 1 for Suspicious unused loop iteration variable
* 1 for Nested loops with same variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ksunden** [comment]
We already do expose it, it is imported in `__init__.py`, LGTM was alerting that we had a `*` import without defining `__all__`

https://lgtm.com/projects/g/wright-group/WrightTools/snapshot/48750bcaaa1e4dd38787fcd8d8b151b56d3e5f4a/files/WrightTools/data/__init__.py?sort=name&dir=ASC&mode=heatmap&showExcluded=false

We expose them for discoverability of their attributes (and to make sure the documentation builds)

**Comment by untzag** [comment]
@ksunden point taken---approved

**Pull request merged**
