### PR TITLE
print tree

### PR DESCRIPTION
**Pull request by untzag**
print a "pretty" tree representation of the contents of a `Collection`

### CODE REVIEW

**Comment by ksunden** [comment]
I did something similar in `h5cli`, https://github.com/ksunden/h5cli/pull/60/

I used https://pypi.python.org/pypi/tree-format to get the formatting done

**Comment by ksunden** [comment]
Some oddities when playing around with this, some of which are not (directly) related to the code here:

1. `col._items` is apparently not updated when `copy` is used to populate a collection. (`items()` and `item_names` are updated, however)
    This results in data objects which are copied in being left out of the tree representation, and the indexes being off.

2. I wonder if it might be useful to include variables and channels from data objects as part of the tree view. (and, perhaps be able to call `print_tree` on a data object itself) This would provide a quick overview of the shape of each constituent component, as well as the whole. Also, it would give a good idea of which variables are available for `transform`

**Comment by untzag** [comment]
@ksunden I think we should open a separate issue for `_items_` propagation

**Comment by ksunden** [comment]
Tested locally because Travis backlog forced them to jettison the queue.

**Pull request merged**
